# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'HelloWorld' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HelloWorld
  pod 'DynamsoftCore','3.2.11'
  pod 'DynamsoftLicense','3.2.11'
  pod 'DynamsoftCameraEnhancer','4.2.1'

end
